### ISSUE TITLE
Chat log management

### ISSUE THREAD

**Issue by erocs** [Civcraft/CivChat#3]
We need to clean up the chat log management.

When the number of txt files goes over filesToZip, all the logs get zipped. Instead it should sort by file date and only zip the oldest files to bring the txt file count back down to filesToZip.

For maxNumberOfZips, we have the config set to 40 but there never seems to be more then about 9.

**Comment by suirad** [comment]
Please close. Duplicate: see https://github.com/Civcraft/CivChat2/issues/15
