### ISSUE TITLE
CivChat Version 2.0

### ISSUE THREAD

**Issue by jjj5311** [Civcraft/CivChat#9]
Okay started working on civchat2 yesterday and got it compiling/loading/running 

What features do we want to keep, lose, add, I know the chat log management issue is something i will address 

Also any code style you want me to use? if anything specific

**Comment by drjawa** [comment]
Ideally, google's java style. https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

Excerpts from jjj5311's message of 2015-03-12 09:46:07 -0700:

**Comment by jjj5311** [comment]
I will try ;)

**Comment by rourke750** [comment]
Keep the range, height stuff, color.  Also the zipping. Don't include
gallow as it isn't needed. Also for commands do it like citadel is and how
it imports from NameLayer.

**Comment by jjj5311** [comment]
https://github.com/jjj5311/CivChat2

Got some of the initial stuff started today... didnt get as far as i would have liked but from here it should be easy ish i think to convert the old commands to the new command style

Please feel free to critique/comment on what i have so far

**Comment by ttk2** [comment]
nice to see some progress.

**Comment by staygroovy57** [comment]
As mentioned in the 03/21 changelog, would love to see the "**/afk**" command be available again as a simple ON/OFF toggle auto-responder that says that "player xyz is now AFK", just the way it used to be with the previous chat system. Many of us were relying on this to inform people of our status in-game.

**Comment by jjj5311** [comment]
What does this all need for marcury

**Comment by ttk2** [comment]
think about cases where it needs to interact with other servers, so Citadel
group messages, or pm's to people on another server.

**Comment by rourke750** [comment]
If you want I can do the mercury stuff.

**Comment by jjj5311** [comment]
What about global chat at the edge of a server?

**Comment by ttk2** [comment]
I don't think we intend to bother with that.

**Comment by jjj5311** [comment]
ok good

**Comment by jjj5311** [comment]
I have made some process on my CivChat2 repo... if anyone wants to work more on this go ahead as I have not had as much time as i would like

**Comment by rourke750** [comment]
What's left to do?

**Comment by jjj5311** [comment]
make sure it works... Groupchat stuff, the height stuff, Mercury stuff, lots of other little things testing will bring up, I didnt test this last commit stuff since i just did it this morning

I will hopefully have some more time next week as i am sure it is jumbled as certain parts are not done right now... there is TODO on the stuff that needs work yet

**Comment by jjj5311** [comment]
@rourke750  I got groupchat working today

**Comment by ttk2** [comment]
locally I assume? I don't think anyone has setup a mercury testbench yet

**Comment by jjj5311** [comment]
yeah nothing with mercury yet... the addition of mercury to this will be very simple

**Comment by jjj5311** [comment]
I think this is ready for testing (still no mercury) with my latest commit... also I believe this will take care of erocs issue with the chat log management #3

**Comment by jjj5311** [comment]
also this is 1.8 compatible

**Comment by ttk2** [comment]
is this being built on the build server?

**Comment by rourke750** [comment]
Not yet.

**Comment by jjj5311** [comment]
no, still under my repo and i dont know how to maven

**Comment by rourke750** [comment]
@jjj5311 So just mercury left?  If so I'm going to clone this to Civcraft.

**Comment by jjj5311** [comment]
Yep just mercury, and the inevitable bugs that i missed that will show up during testing

**Comment by ttk2** [comment]
this is on the 1.8 testing server, just noting that.

**Comment by jjj5311** [comment]
@ttk2 This is not on the test server (if you are talking about Civtest?)

Also I pushed some more commits today to take care of some small issues

**Comment by ttk2** [comment]
if this is the latest jenkins build then yes it is.

**Comment by jjj5311** [comment]
I dont think this is on jenkins yet... Rourke said he was gonna clone it
but looks like he hasn't yet

**Comment by ttk2** [comment]
its on jenkins now, going to put it up there later.
